### ISSUE TITLE
Failed to load the theos-build-manager package

### ISSUE THREAD

**Issue by alxtr1bal** [jaysan1292/theos-manager#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.0-beta0
**System**: Mac OS X 10.11.1
**Thrown From**: [theos-build-manager](https://github.com/jaysan1292/theos-manager) package, v0.4.1
### Stack Trace

Failed to load the theos-build-manager package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/Alex/.atom/packages/theos-build-manager/lib/header-view.coffee:1:1)
    at /Users/Alex/.atom/packages/theos-build-manager/lib/header-view.coffee:5:2
    at Object.<anonymous> (/Users/Alex/.atom/packages/theos-build-manager/lib/header-view.coffee:5:2)
    at Object.<anonymous> (/Users/Alex/.atom/packages/theos-build-manager/lib/header-view.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.13
minimap, v4.16.0
pigments, v0.18.1
theos-build-manager, v0.4.1

# Dev
No dev packages
```

**Comment by afnanahmad** [comment]
I'm also having above issue. Following is the stack trace.

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [theos-build-manager](https://github.com/jaysan1292/theos-manager) package, v0.4.1

### Stack Trace

Failed to load the theos-build-manager package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/afnanahmad/.atom/packages/theos-build-manager/lib/header-view.coffee:1:1)
    at /Users/afnanahmad/.atom/packages/theos-build-manager/lib/header-view.coffee:5:2
    at Object.<anonymous> (/Users/afnanahmad/.atom/packages/theos-build-manager/lib/header-view.coffee:5:2)
    at Object.<anonymous> (/Users/afnanahmad/.atom/packages/theos-build-manager/lib/header-view.coffee:1:1)
    at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/afnanahmad/.atom/packages/theos-build-manager/lib/theos-output-view.coffee:2:14)
    at Object.<anonymous> (/Users/afnanahmad/.atom/packages/theos-build-manager/lib/theos-output-view.coffee:1:1)
    at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/afnanahmad/.atom/packages/theos-build-manager/lib/theos-manager.coffee:1:19)
    at Object.<anonymous> (/Users/afnanahmad/.atom/packages/theos-build-manager/lib/theos-manager.coffee:1:1)
    at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.20.8
language-ini, v1.16.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
nuclide, v0.135.0
theos-build-manager, v0.4.1
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by btraas** [comment]
+1
